/**
 * 알림 서비스 (notification_flow.md 기반)
 *
 * 채널 우선순위:
 *   1. Push (FCM) — 즉시
 *   2. KakaoTalk — 즉시
 *   3. Email (SendGrid) — 백업
 *   4. SMS — 긴급만
 */

import { createServerClient } from "@/lib/supabase/server";

export type NotificationType =
  | "unresponsive"   // 무응답 알림 (보호자)
  | "risk_alert"     // 위험도 상승 (복지사)
  | "action_needed"; // 조치 필요 (복지사)

interface SendNotificationOptions {
  recipientId: string;
  clientId: string;
  type: NotificationType;
  message: string;
  channel: "push" | "email" | "sms" | "kakao";
  isAutoGenerated?: boolean;
}

// 알림 발송 + DB 기록
export async function sendNotification(opts: SendNotificationOptions) {
  const supabase = createServerClient();

  // 1. 중복 발송 방지: 최근 24h 이내 같은 타입 알림이 있으면 skip
  const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  const { data: existing } = await supabase
    .from("notifications")
    .select("id")
    .eq("recipient_id", opts.recipientId)
    .eq("client_id", opts.clientId)
    .eq("type", opts.type)
    .gte("sent_at", yesterday)
    .limit(1);

  if (existing && existing.length > 0) {
    console.log(`[Notification] Skipped duplicate: ${opts.type} for ${opts.clientId}`);
    return { skipped: true };
  }

  // 2. 실제 채널 발송 (외부 API)
  await dispatchChannel(opts);

  // 3. 알림 기록 DB 저장
  const { data, error } = await supabase.from("notifications").insert({
    recipient_id: opts.recipientId,
    client_id: opts.clientId,
    type: opts.type,
    channel: opts.channel,
    message: opts.message,
    is_auto_generated: opts.isAutoGenerated ?? true,
  }).select().single();

  if (error) {
    console.error("[Notification] DB insert error:", error);
  }

  return { sent: true, id: data?.id };
}

async function dispatchChannel(opts: SendNotificationOptions) {
  switch (opts.channel) {
    case "push":
      await sendPushNotification(opts.recipientId, opts.message);
      break;
    case "kakao":
      // KakaoTalk 채널 메시지 (Phase 2에서는 stub)
      console.log(`[Kakao Notify] → ${opts.recipientId}: ${opts.message}`);
      break;
    case "email":
      // SendGrid (Phase 2에서는 stub)
      console.log(`[Email Notify] → ${opts.recipientId}: ${opts.message}`);
      break;
    case "sms":
      console.log(`[SMS Notify] → ${opts.recipientId}: ${opts.message}`);
      break;
  }
}

async function sendPushNotification(userId: string, message: string) {
  // FCM 발송 (환경변수: FIREBASE_SERVER_KEY)
  const fcmKey = process.env.FIREBASE_SERVER_KEY;
  if (!fcmKey) {
    console.log(`[FCM] Key not set — stub send to ${userId}: ${message}`);
    return;
  }

  // 실제 FCM 연동 시 device token 필요 (users 테이블에 fcm_token 컬럼 추가)
  // Phase 2 stub: 로그만 출력
  console.log(`[FCM] → ${userId}: ${message}`);
}

// ─────────────────────────────────────────
// 시나리오별 알림 생성 헬퍼
// notification_flow.md 섹션 4 기반
// ─────────────────────────────────────────

// 보호자에게 무응답 알림
export async function notifyGuardianUnresponsive(
  guardianId: string,
  clientId: string,
  clientName: string,
  workerName: string,
  workerPhone: string
) {
  const message =
    `안녕하세요.\n` +
    `어머니/아버지 ${clientName}님의 응답이 오늘 아직 없어요.\n` +
    `담당 복지사 ${workerName}님도 함께 확인하고 있습니다.\n` +
    `걱정되시면 ${workerPhone}으로 연락 주세요.`;

  return sendNotification({
    recipientId: guardianId,
    clientId,
    type: "unresponsive",
    message,
    channel: "push",
    isAutoGenerated: true,
  });
}

// 복지사에게 위험도 상승 알림
export async function notifyWorkerRiskAlert(
  workerId: string,
  clientId: string,
  clientName: string,
  riskScore: number,
  riskFactors: string[]
) {
  const factorText = riskFactors.slice(0, 2).join(", ");
  const message =
    `🔴 ${clientName}님 위험도 상승 (${riskScore}점)\n` +
    `주요 원인: ${factorText}\n` +
    `오늘 중 확인이 필요합니다.`;

  return sendNotification({
    recipientId: workerId,
    clientId,
    type: "risk_alert",
    message,
    channel: "push",
    isAutoGenerated: true,
  });
}

// 보호자 알림 초안 자동 생성 (복지사 검토용)
export function generateGuardianNotifyDraft(
  clientName: string,
  workerName: string,
  workerPhone: string,
  reason: "unresponsive" | "warning"
): string {
  if (reason === "unresponsive") {
    return (
      `안녕하세요.\n\n` +
      `${clientName}님의 담당 복지사 ${workerName}입니다.\n\n` +
      `오늘 안부 연락을 드렸으나 연결이 어려웠습니다.\n` +
      `직접 연락해보시거나 걱정되시면 저에게 연락 주세요.\n\n` +
      `담당 복지사 ${workerName}\n${workerPhone}`
    );
  }
  return (
    `안녕하세요.\n\n` +
    `${clientName}님의 최근 상태에 변화가 감지되어\n` +
    `연락드립니다. 담당 복지사가 확인 중입니다.\n\n` +
    `담당 복지사 ${workerName}\n${workerPhone}`
  );
}
